# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'archive',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AddField(
            model_name='archive',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.Student'),
        ),
    ]
