# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='commentnums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='vistnums',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='lastlogin',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 29, 16, 25, 8, 772058)),
        ),
    ]
