# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('uage', models.IntegerField(default=20, max_length=6)),
            ],
        ),
    ]
