# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='group1',
        ),
    ]
