# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10, unique=True)),
                ('sname', models.CharField(max_length=50, null=True)),
                ('ssex', models.CharField(default='男', max_length=2)),
                ('sage', models.IntegerField(default=0, null=True)),
                ('sclass', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
