# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('ccredit', models.FloatField(null=True)),
            ],
            managers=[
                ('cmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
