# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.NullBooleanField(default=False),
        ),
    ]
